'use strict';
const data=window.DRAWING_DATA,currentId=document.body.dataset.module||'home',current=data.modules.find(m=>m.id===currentId),isHome=!current;
const directoryModules=[{id:'clothing',title:'服装',file:'服装参考资料目录.html',accent:'#6d28d9',categories:[{title:'历史考据'},{title:'穿着规范'}]},...data.modules];
const readingLevel=document.getElementById('readingLevel');
let geoFilters=null,drawingMapData=null;
function activeReading(){return geoFilters?.active?geoFilters.facets().reading:readingLevel.value}
function activeDateOrder(){return geoFilters?.active?geoFilters.facets().dateOrder:dateOrder.value}
function readingMatches(i){const value=activeReading();return value==='all'||(value==='topics'?!!i.topic:!i.topic)}
const q=document.getElementById('q'),categoryFilter=document.getElementById('categoryFilter'),moduleFilter=document.getElementById('moduleFilter');
const list=document.getElementById('list'),empty=document.getElementById('empty'),userStatus=document.getElementById('userStatus');
function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function usesOfficialImage(im){return /^https:\/\/(?:framemark|iiif)\.vam\.ac\.uk\//.test(im.full||'')}
function imageDisplaySource(im){return usesOfficialImage(im)?im.full:im.src}
function readStore(key,fallback){try{const value=localStorage.getItem('drawing-reference:'+key);return value===null?fallback:JSON.parse(value)}catch{return fallback}}
function saveStore(key,value){try{localStorage.setItem('drawing-reference:'+key,JSON.stringify(value));return true}catch{userStatus.textContent='当前浏览器无法保存设置；收藏清单可先导出。';return false}}
const savedFavorites=readStore('favorites:v1',[]),favorites=new Set(Array.isArray(savedFavorites)?savedFavorites.filter(v=>data.items.some(i=>i.id===v)):[]);
let onlyFavorites=false,searchTimer,composing=false;let viewMode=readStore('view:v1','detail');if(viewMode!=='compact')viewMode='detail';const imageFilter=document.getElementById('imageFilter'),openAudits=new Set();const visibleLimits=new Map(),expandedItems=new Set();const batchSize=10000;function focusOf(i){return i.topic?'专题考据':i.focus==='考据向'?'单件来历':i.focus||'资料入口'}function moduleCount(id){return data.items.filter(i=>i.module===id).length}
const aliases=[['琵琶','pipa'],['房屋','house','houses'],['楼梯','stair','stairs'],['门窗','window','doorway'],['椅子','chair'],['灯具','lamp','lighting'],['骨骼','skeleton'],['鸟翼','wing','wings'],['植物','plant','botanical'],['坐姿','sitting','seated'],['持物','holding'],['多人','group'],['钢琴','piano']];
function folded(v){return String(v).normalize('NFD').replace(/\p{M}/gu,'').toLowerCase()}
function searchTerms(value){return value.trim().split(/\s+/).filter(Boolean).map(t=>aliases.find(g=>g.some(w=>folded(w)===folded(t)))||[t])}
function moduleOf(item){return data.modules.find(m=>m.id===item.module)}
function categoryOf(item){return moduleOf(item).categories.find(c=>c.id===item.category)}
function searchable(item){return folded([item.topic?JSON.stringify(item.topic):'',Object.values(window.DRAWING_ORGANIZATION?.items[item.id]||{}).filter(v=>typeof v==='string').join(' '),item.name,item.url,item.region,item.period,item.kind,focusOf(item),(item.facts||[]).map(f=>f.label+":"+f.value).join(" "),(item.detailNotes||[]).map(n=>n.part+":"+n.note).join(" "),item.content,item.use,item.caution,item.find,item.collect,moduleOf(item).title,categoryOf(item).title].join(' '))}
function option(value,title){return `<option value="${esc(value)}">${esc(title)}</option>`}
const scopedItems=isHome?data.items:data.items.filter(i=>i.module===current.id);
const organization=window.DRAWING_ORGANIZATION,regionFilter=document.getElementById('regionFilter'),countryFilter=document.getElementById('countryFilter'),eraFilter=document.getElementById('eraFilter'),dateOrder=document.getElementById('dateOrder');
const organizationEnabled=!!organization&&!isHome&&['architecture','objects'].includes(currentId),openCountries=new Map();
function organizationFilters(){return {region:regionFilter.value||'all',country:countryFilter.value||'all',era:eraFilter.value||'all'}}
function organizationActive(){return organizationEnabled&&Object.values(organizationFilters()).some(v=>v!=='all')}
function organizationItems(){return scopedItems.filter(i=>(readingLevel.value==='all'||(readingLevel.value==='topics'?!!i.topic:!i.topic))&&organization.isTarget(i)&&(categoryFilter.value==='all'||i.module+':'+i.category===categoryFilter.value))}
function syncOrganizationOptions(){
 if(!organizationEnabled)return;
 const items=organizationItems(),oldRegion=regionFilter.value||'all',oldCountry=countryFilter.value||'all',oldEra=eraFilter.value||'all';
 const regions=organization.regions.filter(r=>items.some(i=>organization.items[i.id].region===r));regionFilter.innerHTML=option('all','全部大区')+regions.map(r=>option(r,r)).join('');regionFilter.value=regions.includes(oldRegion)?oldRegion:'all';
 const countries=[...new Set(items.filter(i=>regionFilter.value==='all'||organization.items[i.id].region===regionFilter.value).map(i=>organization.items[i.id].country))].sort((a,b)=>a.localeCompare(b,'zh-CN'));
 countryFilter.innerHTML=option('all','全部国家／地区')+countries.map(c=>option(c,c)).join('');countryFilter.value=countries.includes(oldCountry)?oldCountry:'all';
 const eraItems=items.filter(i=>(regionFilter.value==='all'||organization.items[i.id].region===regionFilter.value)&&(countryFilter.value==='all'||organization.items[i.id].country===countryFilter.value));
 const eras=[...new Set(organization.sort(eraItems).map(i=>organization.items[i.id].era))];eraFilter.innerHTML=option('all','全部时代')+eras.map(e=>option(e,e)).join('');eraFilter.value=eras.includes(oldEra)?oldEra:'all';
 for(const label of document.querySelectorAll('[data-organization]'))label.hidden=items.length===0;

}
function regionalHtml(items,cat){
 const sorted=sortDrawingItems(items),countries=new Map();for(const i of sorted){const n=organization.items[i.id],key=n.region+'|'+n.country;if(!countries.has(key))countries.set(key,{region:n.region,country:n.country,items:[]});countries.get(key).items.push(i)}
 return {shown:items.length,html:organization.regions.map(region=>[...countries.values()].filter(g=>g.region===region).sort((a,b)=>a.country.localeCompare(b.country,'zh-CN')).map(g=>`<div class="region-block" data-region-group="${esc(region)}" data-country-group="${esc(g.country)}"><h3 class="region-head">${esc(g.region)} · ${esc(g.country)}<span>${g.items.length} 条</span></h3>${g.items.map(cardHtml).join('')}</div>`).join('')).join('')};
}
function sortDrawingItems(items){
 if(!geoFilters?.active)return organization.sort(items,dateOrder.value);
 const start=item=>{const ranges=drawingMapData.byId.get(item.id).date.ranges;return ranges.length?Math.min(...ranges.map(range=>range[0])):null};
 return [...items].sort((a,b)=>{const x=start(a),y=start(b);if(x===null||y===null)return x===y?a.name.localeCompare(b.name,'zh-CN'):x===null?1:-1;return (x-y)*(activeDateOrder()==='desc'?-1:1)||a.name.localeCompare(b.name,'zh-CN')});
}
function setupDrawingMap(){
 if(!window.ClothingMapFilters||!window.DrawingMapAdapter||!window.REFERENCE_WORLD_REGIONS){
  document.getElementById('mapPanel').hidden=true;document.querySelector('[data-filter-mode=map]').disabled=true;document.querySelector('[data-filter-mode=text]').setAttribute('aria-pressed','true');userStatus.textContent='地图资源未加载，可继续使用文字筛选。';return;
 }
 drawingMapData=window.DrawingMapAdapter.build(scopedItems,organization,window.REFERENCE_WORLD_REGIONS);
 const categoryDefs=(isHome?data.modules:[current]).flatMap(m=>m.categories.map(c=>({key:m.id+':'+c.id,title:isHome?m.title+' · '+c.title:c.title})));
 const facets=[
  {key:'reading',id:'mapReading',title:'资料',default:readingLevel.value,options:[{key:'topics',title:'中文专题考据'},{key:'examples',title:'实物与来源'},{key:'all',title:'全部资料'}]},
  {key:'category',id:'mapCategory',title:'分类',options:[{key:'all',title:'全部分类'},...categoryDefs]},
  {key:'image',id:'mapImage',title:'例图',options:[{key:'all',title:'全部例图'},{key:'yes',title:'有例图'},{key:'no',title:'无例图'}]},
  ...(isHome?[{key:'module',id:'mapModule',title:'模块',options:[{key:'all',title:'全部模块'},...data.modules.map(m=>({key:m.id,title:m.title}))]}]:[]),
  {key:'dateOrder',id:'mapDateOrder',title:'年代顺序',default:'asc',options:[{key:'asc',title:'从早到晚'},{key:'desc',title:'从晚到早'}]}
 ];
 geoFilters=window.ClothingMapFilters({...drawingMapData,facets,getDate:record=>record.date,
  note:currentId==='nature'?'通用生物结构不限定年代；机构所在地、扫描日期不代表物种的地区或年代。':currentId==='people'?'通用动作不限定年代；历史图像按原有制作或出版时间匹配。':'地区与年代优先使用现有来源记录；不确定归属保留在“地区未详”。',
  onChange:()=>{clearTimeout(searchTimer);visibleLimits.clear();render()},getShared:()=>({q:q.value,favorites:onlyFavorites}),setShared:state=>{clearTimeout(searchTimer);composing=false;q.value=state.q;onlyFavorites=state.favorites}
 });
}

function init(){
 
 document.getElementById('pageTitle').textContent=isHome?'绘画参考资料目录':current.title+'参考资料';
 document.getElementById('headerMeta').textContent=`${scopedItems.filter(i=>i.topic).length} 篇专题 · ${scopedItems.filter(i=>!i.topic).length} 项实物与来源`;
 document.getElementById('breadcrumb').innerHTML=isHome?'':`<a href="绘画参考资料首页.html">总首页</a> / ${esc(current.title)}`;
 moduleFilter.innerHTML=option('all','全部模块')+data.modules.map(m=>option(m.id,m.title)).join('');
 document.getElementById('moduleFilterLabel').hidden=!isHome;
 const categoryDefs=(isHome?data.modules:[current]).flatMap(m=>m.categories.map(c=>({key:m.id+':'+c.id,label:isHome?m.title+' · '+c.title:c.title})));
 categoryFilter.innerHTML=option('all','全部分类')+categoryDefs.map(c=>option(c.key,c.label)).join('');
 document.getElementById('tocBody').innerHTML=`<a href="绘画参考资料首页.html" ${isHome?'class="current" aria-current="page"':''}>总首页</a>`+directoryModules.map(m=>`<a href="${esc(m.file)}" ${currentId===m.id?'class="current" aria-current="page"':''}>${esc(m.title)}</a>${currentId===m.id?m.categories.map(c=>`<a class="toc-category" href="#cat-${esc(c.id)}">${esc(c.title)} <small data-toc-count="${esc(c.id)}"></small></a>`).join(''):''}`).join('');
 if(isHome){document.getElementById('modules').innerHTML=`<div class="module-grid">`+directoryModules.map(m=>`<a class="module-card" href="${esc(m.file)}" style="--module-accent:${m.accent}"><div class="module-preview">${m.id==='clothing'?'<span class="module-symbol" aria-hidden="true">衣</span>':(data.items.find(i=>i.id===({architecture:'arch-damascus',objects:'obj-pipa',people:'pose-maniacs',nature:'nature-kestrel'})[m.id])?.images||[]).slice(0,1).map(im=>`<img src="${esc(imageDisplaySource(im))}" alt="${esc(im.caption)}" loading="lazy">`).join('')}</div><h3>${esc(m.title)}</h3><p>${m.categories.map(c=>esc(c.title)).join(' · ')}</p></a>`).join('')+`</div>`;}
 const requestedReading=new URLSearchParams(location.search).get('reading');if(['topics','examples','all'].includes(requestedReading))readingLevel.value=requestedReading;
 if(location.hash==='#organizationPanel')history.replaceState(null,'',location.pathname+location.search);
 for(const label of document.querySelectorAll('[data-organization]'))label.hidden=!organizationEnabled;setView(viewMode,false);syncOrganizationOptions();setupDrawingMap();render();document.body.dataset.ready='true';setToc(wideScreen.matches);updateToolbarSpace();
 if(location.hash){const target=data.items.find(i=>i.id===decodeURIComponent(location.hash.slice(1)));if(target){expandedItems.add(target.id);if(!target.topic){readingLevel.value='examples';if(geoFilters?.active)document.getElementById('mapReading').value='examples';visibleLimits.set(target.category,1000);if(organization?.isTarget(target)){const nav=organization.items[target.id];const key=target.category+':'+nav.region+':'+nav.country;visibleLimits.set(key,1000);openCountries.set(key,true)}}syncOrganizationOptions();render()}requestAnimationFrame(()=>document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView())}
}
function imageCaption(im){return im.caption+' ｜ '+im.provider}
function imagesHtml(item){return item.images?.length?`<div class="thumbs">${item.images.map((im,index)=>{const cap=imageCaption(im);return `<figure><a class="thumb" href="${esc(im.full)}" data-item="${esc(item.id)}" data-index="${index}" target="_blank" rel="noopener noreferrer" aria-label="查看大图：${esc(cap)}"><img src="${esc(imageDisplaySource(im))}" data-full="${esc(im.full)}" alt="${esc(cap)}" width="120" height="150" loading="lazy" decoding="async" referrerpolicy="no-referrer"><span class="thumb-message" aria-hidden="true">加载中</span></a><figcaption>${esc(cap)}<br><a class="source-link" href="${esc(im.source)}" target="_blank" rel="noopener noreferrer">图源 ↗</a></figcaption></figure>`}).join('')}</div><div class="image-actions"><a class="source-link" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer">查看资料来源 ↗</a><span>点击例图，连续查看大图</span></div>`:''}
function topicContent(item){
 const t=item.topic,refs=ids=>ids.map(id=>{const n=t.sources.findIndex(s=>s.id===id),r=t.sources[n];return r?` <a class="fact-ref" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer" title="${esc(r.title+'；'+r.locator)}">[${n+1}]</a>`:''}).join('');
 const examples=(t.examples||[]).map(id=>data.items.find(i=>i.id===id)).filter(Boolean);
 return `<div class="topic-body"><p class="topic-scope">${esc(t.scope)}</p><section class="topic-common"><h4>共同特征</h4><ol>${t.common.map(r=>`<li><b>${esc(r.title)}</b><p>${esc(r.text)}${refs(r.refs)}</p></li>`).join('')}</ol></section><section><h4>类型差异</h4><table class="topic-types"><thead><tr><th>类型</th><th>特征</th></tr></thead><tbody>${t.types.map(r=>`<tr><th scope="row">${esc(r.name)}</th><td>${esc(r.feature)}${refs(r.refs)}</td></tr>`).join('')}</tbody></table></section><section><h4>形成原因</h4>${t.why.map(r=>`<p>${esc(r.text)}${refs(r.refs)}</p>`).join('')}</section><section><h4>适用范围</h4><ul>${t.limits.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></section><section><h4>绘画参考</h4><p>${esc(t.drawing)}</p></section><section class="topic-sources"><h4>依据与原文</h4><ol>${t.sources.map(r=>`<li><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)} ↗</a><p>${esc(r.locator)}</p></li>`).join('')}</ol></section>${examples.length?`<section class="topic-examples"><h4>实物例证</h4><ul>${examples.map(e=>`<li><a href="${esc(moduleOf(e).file)}?reading=examples#${esc(e.id)}">${esc(e.name)}</a> · ${esc(e.period)}</li>`).join('')}</ul></section>`:''}</div>`;
}
function recordNotes(item){return `${item.facts?.length?`<div class="source-facts"><h4>来源事实</h4><dl>${item.facts.map(f=>`<div><dt>${esc(f.label)}</dt><dd>${esc(f.value)} <a href="${esc(f.source)}" target="_blank" rel="noopener noreferrer">↗</a></dd></div>`).join('')}</dl></div>`:''}${item.detailNotes?.length?`<div class="detail-notes"><h4>细节说明</h4>${item.detailNotes.map(n=>`<p><b>${esc(n.part)}</b>${esc(n.note)}</p>`).join('')}</div>`:''}<p>${esc(item.check)}</p><p class="intro-row"><b>怎么查找</b><span>${esc(item.find)}</span></p><p class="intro-row"><b>收集重点</b><span>${esc(item.collect)}</span></p>`}
function cardHtml(item){
 const on=favorites.has(item.id),m=moduleOf(item),c=categoryOf(item),nav=organization?.items[item.id],tags=[nav?nav.country:item.region,nav?nav.dateLabel:item.period,c.title,item.kind],expanded=expandedItems.has(item.id);
 return `<article class="item${item.topic?' topic-card':''}${expanded?' details-open':''}" id="${esc(item.id)}"><div class="badges"><div class="lv ${item.topic?'topic':'example'}">${item.topic?'专题':'资料'}</div><div class="st">${item.images?.length?'有图':'原文'}</div></div><div class="body"><div class="card-heading"><h4 class="name"><a href="${esc(item.url)}" target="_blank" rel="noopener noreferrer">${esc(item.name)}</a></h4><button class="favorite-btn" type="button" data-item="${esc(item.id)}" aria-pressed="${on}" aria-label="${on?'取消收藏：':'收藏：'}${esc(item.name)}">${on?'★ 已收藏':'☆ 收藏'}</button></div><div class="url">${esc(item.url)}</div><div class="meta-tags">${tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="intro"><p class="intro-row intro-content"><b>资料内容</b><span>${esc(item.content)}</span></p><p class="intro-row intro-use"><b>绘画用途</b><span>${esc(item.use)}</span></p><p class="intro-row intro-caution caution"><b>使用提醒</b><span>${esc(item.caution)}</span></p></div><button type="button" class="detail-toggle" data-item="${esc(item.id)}" aria-expanded="${expanded}">${expanded?'收起完整介绍':'展开完整介绍'}</button>${imagesHtml(item)}<div class="check-dates"><span>整理日期：${esc(data.date)}</span><span>${item.topic?'专题依据：见正文逐项引用':'来源记录：'+esc(item.check)}</span></div><details class="audit" ${openAudits.has(item.id)?'open':''}><summary>${item.topic?'查看专题正文与依据':'查看来源核查记录'}</summary><div class="note">${item.topic?topicContent(item):recordNotes(item)}</div></details></div></article>`;
}
function render(){const terms=searchTerms(q.value),mapMode=!!geoFilters?.active,facets=mapMode?geoFilters.facets():{category:categoryFilter.value,module:moduleFilter.value,image:imageFilter.value,reading:readingLevel.value,dateOrder:dateOrder.value},cat=facets.category,mod=facets.module||'all';
 const active=facets.reading!=='topics'||!!terms.length||cat!=='all'||(isHome&&mod!=='all')||onlyFavorites||facets.image!=='all'||(mapMode?geoFilters.activeCount()>0:organizationActive()||(organizationEnabled&&dateOrder.value==='desc'));
 const eligible=i=>readingMatches(i)&&(facets.image==='all'||(facets.image==='yes'?i.images?.length:!i.images?.length))&&(!isHome||mod==='all'||i.module===mod)&&(cat==='all'||i.module+':'+i.category===cat)&&(!onlyFavorites||favorites.has(i.id))&&terms.every(group=>group.some(term=>searchable(i).includes(folded(term))));
 const matches=scopedItems.filter(i=>eligible(i)&&(mapMode?geoFilters.matches(drawingMapData.byId.get(i.id)):!organizationEnabled||organization.matches(i,organizationFilters())));
 const starters=new Set(data.modules.flatMap(m=>m.start));const candidates=isHome&&!active?matches.filter(i=>starters.has(i.id)):matches;let shown=0;
 document.getElementById('modules').hidden=!isHome||active;
 document.getElementById('listHeading').textContent=isHome&&!active?'精选专题':(facets.reading==='topics'?'专题考据':'参考资料');document.getElementById('listHeading').hidden=!isHome;
 if(isHome){const cap=active?(visibleLimits.get('home')||24):candidates.length;const display=(mapMode?sortDrawingItems(candidates):candidates).slice(0,cap);shown=display.length;list.innerHTML=display.map(cardHtml).join('')+(candidates.length>cap?`<button class="load-more" type="button" data-more="home">更多资料（${cap}/${candidates.length}）</button>`:'');}
 else{list.innerHTML=current.categories.map(c=>{const items=candidates.filter(i=>i.category===c.id),regional=facets.reading!=='topics'&&organizationEnabled&&(currentId==='architecture'||c.id==='vessels'),cap=visibleLimits.get(c.id)||batchSize,display=(mapMode||organizationEnabled&&organization.isTarget(items[0]||{})?sortDrawingItems(items):items).slice(0,cap),grouped=regional?regionalHtml(items,c.id,active):null;shown+=grouped?grouped.shown:display.length;return items.length?`<section class="category-section" id="cat-${esc(c.id)}"><h2 class="category-head">${esc(c.title)}<span>${items.length} 条</span></h2>${grouped?grouped.html:display.map(cardHtml).join('')}${!grouped&&items.length>cap?`<button class="load-more" type="button" data-more="${esc(c.id)}">更多资料（${cap}/${items.length}）</button>`:''}</section>`:''}).join('');for(const c of current.categories){const n=candidates.filter(i=>i.category===c.id).length;const counter=document.querySelector(`[data-toc-count="${c.id}"]`);counter.textContent=n;counter.closest('a').hidden=n===0;}}
 empty.hidden=candidates.length!==0;document.getElementById('resultCount').hidden=false;document.getElementById('resultCount').textContent=`当前找到 ${matches.length} 条 / 全库 ${scopedItems.length} 条${onlyFavorites?' · 仅看收藏':''}`;
 document.getElementById('favoriteCount').textContent=favorites.size;document.getElementById('favoritesOnly').setAttribute('aria-pressed',String(onlyFavorites));document.getElementById('exportFavorites').disabled=favorites.size===0;document.getElementById('clearFilters').disabled=!active;
 const n=mapMode?geoFilters.activeCount():[readingLevel.value!=='topics',imageFilter.value!=='all',cat!=='all',isHome&&mod!=='all',organizationActive(),organizationEnabled&&dateOrder.value==='desc'].filter(Boolean).length;document.getElementById('activeFilterCount').textContent=n?`已选 ${n} 项`:'';
 const summary=mapMode?geoFilters.summary():[readingLevel.selectedOptions[0]?.textContent,categoryFilter.selectedOptions[0]?.textContent,...(isHome?[moduleFilter.selectedOptions[0]?.textContent]:[]),...(organizationEnabled?Object.entries(organizationFilters()).filter(([,v])=>v!=='all').map(([,v])=>v):[]),...(imageFilter.value!=='all'?[imageFilter.selectedOptions[0]?.textContent]:[])].filter(Boolean).join(' · ');
 document.getElementById('filterSummary').textContent=(mapMode?'地图：':'文字：')+summary+(q.value?' · 搜索：'+q.value:'')+(onlyFavorites?' · 仅看收藏':'');geoFilters?.update(matches.length,record=>eligible(record.original));highlightResults(terms);updateToolbarSpace();
}
function resetFilters(){clearTimeout(searchTimer);q.value='';onlyFavorites=false;visibleLimits.clear();userStatus.textContent='';if(geoFilters?.active){geoFilters.reset()}else{imageFilter.value='all';readingLevel.value='topics';categoryFilter.value=moduleFilter.value='all';regionFilter.value=countryFilter.value=eraFilter.value='all';dateOrder.value='asc';openCountries.clear();syncOrganizationOptions()}render();q.focus()}
function favoriteCsv(){const headings=['资料名称','所属模块','子类','资料方向','资料性质','地区','时期','来源网址','绘画用途','怎么查找','收集重点','使用提醒'];const rows=data.items.filter(i=>favorites.has(i.id)).map(i=>[i.name,moduleOf(i).title,categoryOf(i).title,focusOf(i),i.kind,i.region,i.period,i.url,i.use,i.find,i.collect,i.caution]);const cell=v=>'"'+String(v).replace(/"/g,'""')+'"';return '\ufeff'+[headings,...rows].map(row=>row.map(cell).join(',')).join('\r\n')}
function queueSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{visibleLimits.clear();render()},180)}
q.addEventListener('compositionstart',()=>{composing=true;clearTimeout(searchTimer)});q.addEventListener('compositionend',()=>{composing=false;queueSearch()});q.addEventListener('input',()=>{if(!composing)queueSearch()});
for(const select of [readingLevel,categoryFilter,moduleFilter,imageFilter])select.addEventListener('change',()=>{clearTimeout(searchTimer);if(select===readingLevel)openCountries.clear();visibleLimits.clear();syncOrganizationOptions();render()});
for(const select of [regionFilter,countryFilter,eraFilter,dateOrder])select.addEventListener('change',()=>{clearTimeout(searchTimer);visibleLimits.clear();syncOrganizationOptions();render()});
document.getElementById('clearFilters').addEventListener('click',resetFilters);document.getElementById('emptyReset').addEventListener('click',resetFilters);
document.getElementById('favoritesOnly').addEventListener('click',()=>{onlyFavorites=!onlyFavorites;clearTimeout(searchTimer);render()});

document.getElementById('exportFavorites').addEventListener('click',()=>{if(!favorites.size)return;const url=URL.createObjectURL(new Blob([favoriteCsv()],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='绘画参考收藏清单.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);userStatus.textContent=`已导出 ${favorites.size} 条收藏。`});
list.addEventListener('toggle',e=>{if(e.target.matches('.audit')&&e.target.isConnected){const id=e.target.closest('.item').id;e.target.open?openAudits.add(id):openAudits.delete(id)}},true);
list.addEventListener('click',e=>{
 const more=e.target.closest('[data-more]');if(more){visibleLimits.set(more.dataset.more,(visibleLimits.get(more.dataset.more)||24)+24);render();return}
 const fav=e.target.closest('.favorite-btn');if(fav){const id=fav.dataset.item;favorites.has(id)?favorites.delete(id):favorites.add(id);saveStore('favorites:v1',[...favorites]);if(onlyFavorites)render();else{const on=favorites.has(id);fav.setAttribute('aria-pressed',String(on));fav.textContent=on?'★ 已收藏':'☆ 收藏';fav.setAttribute('aria-label',(on?'取消收藏：':'收藏：')+data.items.find(i=>i.id===id).name);document.getElementById('favoriteCount').textContent=favorites.size;document.getElementById('exportFavorites').disabled=!favorites.size}return}
 const detail=e.target.closest('.detail-toggle');if(detail){const card=detail.closest('.item'),on=card.classList.toggle('details-open');on?expandedItems.add(card.id):expandedItems.delete(card.id);detail.setAttribute('aria-expanded',String(on));detail.textContent=on?'收起完整介绍':'展开完整介绍';return}
 const thumb=e.target.closest('a.thumb');if(!thumb||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();openLb(thumb);
});
function setView(mode,save=true){viewMode=mode;document.body.classList.toggle('compact-view',mode==='compact');document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));if(save)saveStore('view:v1',mode)}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lbImg'),lbCap=document.getElementById('lbCap'),lbStatus=document.getElementById('lbStatus'),lbOriginal=document.getElementById('lbOriginal'),lbSource=document.getElementById('lbSource'),lbX=document.getElementById('lbX');
const $wrap=document.getElementById('main'),$toc=document.getElementById('toc'),$tocBtn=document.getElementById('tocBtn'),$tocOverlay=document.getElementById('tocOverlay'),wideScreen=window.matchMedia('(min-width:1280px)'),recordById=new Map(data.items.map(i=>[i.id,i]));let tocOpen=false,lastImageTrigger=null,galleryItem=null,galleryIndex=0;
function highlightResults(terms){if(!terms.length)return;const variants=[...new Set(terms.flat())].filter(Boolean).sort((a,b)=>b.length-a.length),re=new RegExp(variants.map(s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'gi');for(const el of list.querySelectorAll('.name a,.url,.intro-row span,.meta-tags span,figcaption,.topic-body p,.topic-body li,.topic-types td')){const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())if(!walker.currentNode.parentElement.closest('mark'))nodes.push(walker.currentNode);for(const node of nodes){const str=node.nodeValue;let start=0,html='';for(const match of str.matchAll(re)){html+=esc(str.slice(start,match.index))+'<mark>'+esc(match[0])+'</mark>';start=match.index+match[0].length}if(start){html+=esc(str.slice(start));const t=document.createElement('template');t.innerHTML=html;node.replaceWith(t.content)}}}}
function syncInert(){const modal=lb.classList.contains('open');$wrap.inert=modal||(!wideScreen.matches&&tocOpen);$toc.inert=modal||!tocOpen;$tocBtn.inert=modal}
function setToc(open,focus=false){tocOpen=open;$toc.classList.toggle('closed',!open);document.body.classList.toggle('toc-open',open);document.body.classList.toggle('drawer-open',open&&!wideScreen.matches);$tocBtn.classList.toggle('hidden',open);$tocBtn.setAttribute('aria-expanded',String(open));$toc.setAttribute('aria-hidden',String(!open));$tocOverlay.hidden=!open||wideScreen.matches;syncInert();if(focus)(open?document.getElementById('tocClose'):$tocBtn).focus()}
$tocBtn.addEventListener('click',()=>setToc(true,true));document.getElementById('tocClose').addEventListener('click',()=>setToc(false,true));$tocOverlay.addEventListener('click',()=>setToc(false,true));wideScreen.addEventListener('change',()=>setToc(wideScreen.matches));
$toc.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||!a.getAttribute('href').startsWith('#')||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const el=document.querySelector(a.getAttribute('href'));if(!wideScreen.matches)setToc(false);if(el&&!wideScreen.matches){const h=el.querySelector('h2,h3');h.tabIndex=-1;h.focus({preventScroll:true})}});
function updateToolbarSpace(){document.documentElement.style.setProperty('--toolbar-space',`${document.querySelector('.toolbar').offsetHeight+16}px`)}
new ResizeObserver(updateToolbarSpace).observe(document.querySelector('.toolbar'));
function failedThumb(img){const a=img.closest('.thumb');a.dataset.fail='';a.querySelector('.thumb-message').textContent='图暂未显示';img.classList.add('on')}
document.addEventListener('load',e=>{const img=e.target;if(img.tagName!=='IMG')return;if(img.closest('.thumb')){if(img.naturalWidth<=2||img.naturalHeight<=2){failedThumb(img);return}img.classList.add('on');img.closest('.thumb').dataset.loaded='';img.closest('.thumb').removeAttribute('data-fail')}if(img===lbImg){lbStatus.textContent='';lbImg.hidden=false}},true);
document.addEventListener('error',e=>{const img=e.target;if(img.tagName!=='IMG')return;if(img.closest('.thumb')){if(!img.dataset.fallback&&img.getAttribute('src')!==img.dataset.full){img.dataset.fallback='1';img.src=img.dataset.full}else failedThumb(img)}if(img===lbImg&&lb.classList.contains('open')){lbImg.hidden=true;lbStatus.textContent='图片暂时无法显示，可尝试打开原图或查看资料来源。'}},true);
function showGalleryImage(){const im=galleryItem.images[galleryIndex],src=im.full;lbCap.textContent=imageCaption(im)+' ｜ '+im.credit+' ｜ '+im.license;lbImg.alt=lbCap.textContent;lbStatus.textContent='正在加载大图…';lbOriginal.href=src;lbSource.href=im.source;lbImg.hidden=false;document.getElementById('lbIndex').textContent=`${galleryIndex+1} / ${galleryItem.images.length}`;document.getElementById('lbPrev').disabled=document.getElementById('lbNext').disabled=galleryItem.images.length<=1;lbImg.src=src}
function moveGallery(step){if(!galleryItem||galleryItem.images.length<2)return;galleryIndex=(galleryIndex+step+galleryItem.images.length)%galleryItem.images.length;showGalleryImage()}
function openLb(trigger){lastImageTrigger=trigger;galleryItem=recordById.get(trigger.dataset.item);galleryIndex=Number(trigger.dataset.index);lb.classList.add('open');lb.setAttribute('aria-hidden','false');document.body.classList.add('lb-open');syncInert();lbX.focus();showGalleryImage()}
function closeLb(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true');lbImg.removeAttribute('src');document.body.classList.remove('lb-open');syncInert();if(lastImageTrigger?.isConnected)lastImageTrigger.focus();lastImageTrigger=null;galleryItem=null}
document.getElementById('lbPrev').addEventListener('click',()=>moveGallery(-1));document.getElementById('lbNext').addEventListener('click',()=>moveGallery(1));lb.addEventListener('click',e=>{if(e.target===lb||e.target.closest('#lbX'))closeLb()});
let touchPoint=null;lbImg.addEventListener('touchstart',e=>{const t=e.touches[0];touchPoint=t?{x:t.clientX,y:t.clientY}:null},{passive:true});lbImg.addEventListener('touchend',e=>{const t=e.changedTouches[0];if(t&&touchPoint){const dx=t.clientX-touchPoint.x,dy=t.clientY-touchPoint.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.2)moveGallery(dx<0?1:-1)}touchPoint=null},{passive:true});
function trapFocus(e,container){const focusable=[...container.querySelectorAll('button,a[href],input,[tabindex="0"]')].filter(el=>!el.disabled&&!el.hidden&&el.getClientRects().length);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
document.addEventListener('keydown',e=>{if(lb.classList.contains('open')){if(e.key==='Escape')closeLb();else if(e.key==='Tab')trapFocus(e,lb);else if(e.key==='ArrowLeft'){e.preventDefault();moveGallery(-1)}else if(e.key==='ArrowRight'){e.preventDefault();moveGallery(1)}}else if(tocOpen&&!wideScreen.matches){if(e.key==='Escape')setToc(false,true);else if(e.key==='Tab')trapFocus(e,$toc)}});

init();
